on:
  pull_request:
    branches: mastser
  push:

jobs:
  checkstyle_job:
    runs-on: ubuntu-latest
    name: Checkstyle job
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run check style
      uses: nikitasavinov/checkstyle-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        CHECKSTYLE_CONFIG: ./style/google_checks.xml
        level: info
        filter_mode: file
        reporter: 'github-check'
        tool_name: 'testtool'
